### ISSUE TITLE
Missing files in local/ directory

### ISSUE THREAD

**Issue by ramya18p** [displace2024/Displace2024_baseline#3]
For speaker diarization, run.sh calls local/diarize_fbank.sh inturn it expects local/diarization/my_spectral_cluster.sh file which is not present. Also local/diarize_fbank.sh doesn't support --clustering and --scoretype arguments. Please check the code and update it again.

**Comment by displace2024** [comment]
thank you for raising this issue, 

we have resolved it.

**Comment by ramya18p** [comment]
Hi, in the file that was attached there were some more missing files. Can you please run the baseline from your side using this repo and make the changes? There are lot of missing files/name changes, etc.,
