### ISSUE TITLE
More missing files/names in the speaker diarization setup

### ISSUE THREAD

**Issue by ramya18p** [displace2024/Displace2024_baseline#4]
Hi, in the file that was attached for spectral clustering there were some more missing files. Can you please run the baseline from your side using this repo and make the changes? There are lot of missing files/name changes, etc.,

For e.g.
run.sh -> refers exp/xvector_nnet_1a_tdnn_fbank/plda_model_fullpath -> it doesnt exists
my_spectral_cluster.sh -> utils/split_data_mine.sh -> it doesn't exists
local/diarize_fbank.sh -> number of arguments doesnt match and it exits

**Comment by ramya18p** [comment]
Any updates @organizers ?

**Comment by displace2024** [comment]
we have updated the codes
