### ISSUE TITLE
Missing files in /speaker_diarization/data

### ISSUE THREAD

**Issue by Ashh-Z** [displace2024/Displace2024_baseline#5]
I get the following error on running the run.sh script. It seems that some files are missing in the /speaker_diarization/data directory.

statScale=10 loop=0.45 maxiters=1
./run.sh: Performing VB-HMM resegmentation of DEV...
utils/data/convert_data_dir_to_whole.sh: Data directory already does not contain segments. So just copying it.
copy_data_dir.sh: no such file data/displace_dev/utt2spk
local/resegment_vbhmm.sh: Extracting MFCCs....
steps/make_mfcc.sh --nj 27 --cmd run.pl --write-utt2num-frames true --mfcc-config conf/mfcc_vb.conf data/displace_dev_vbhmm_whole exp/make_mfcc/displace_dev_vbhmm_whole exp/make_mfcc/displace_dev_vbhmm_whole
steps/make_mfcc.sh: no such file data/displace_dev_vbhmm_whole/wav.scp

**Comment by displace2024** [comment]
we have updated the codes
