### ISSUE TITLE
Missing: SAD and Overlap pyannote model

### ISSUE THREAD

**Issue by pavanhitloop** [displace2024/Displace2024_baseline#6]
The SAD and Overlap pyannote model bin file is missing in the following path specified in `Displace2024_baseline/tree/main/speaker_diarization/run.sh` (line 37).
>>> pyannote_pretrained_model=../vad_benchmarking/VAD_model/pytorch_model.bin

Also, didn't provide any link to download and place in the `VAD_model` folder.

**Comment by displace2024** [comment]
Download pytorch_model.bin, config.yaml from [pyannote/segmentation-3.0](https://huggingface.co/pyannote/segmentation-3.0) to path vad_benchmarking/VAD_model/
